# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.0.0

# path remapping to support OpenZepplin imports with NPM-style path
compiler:
  solc:
    version: 0.8.0
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.0.0"
